export type ReportCopyKey = keyof typeof REPORT_COPY_KO;

export const REPORT_COPY_KO = {
  "report.rules.overview.summary": "이 리포트는 {dayPillar} 일주를 중심으로 사주 구조를 읽기 쉽게 정리한 설명형 요약입니다. {daySummary}",
  "report.rules.overview.tone.terminology": "사주 용어는 꼭 필요한 범위에서만 사용하고, 바로 이해할 수 있는 설명을 함께 제공합니다.",
  "report.rules.overview.tone.noPrediction": "확정적 예언 대신 경향, 리스크, 준비 방향을 구분해 보여줍니다.",
  "report.rules.overview.disclaimer": "본 리포트는 정보/오락 목적이며, 금융, 의학, 법률 자문이 아닙니다.",
  "report.rules.personality.monthStrength": "월주는 주변 환경과 일의 리듬을 볼 때 참고합니다. {monthSummary}",
  "report.rules.personality.balanceNote": "강점이 커질수록 한쪽 방식에 익숙해질 수 있으므로, 중요한 선택은 다른 관점과 함께 확인하는 편이 좋습니다.",
  "report.rules.career.yearTrend": "연주는 큰 흐름을 보는 참고점입니다. {yearLabel} 성향은 장기 방향을 정리할 때 단서가 됩니다.",
  "report.rules.career.realityRisk": "커리어 판단은 현실 조건, 시장 상황, 건강한 회복 시간과 함께 봐야 합니다.",
  "report.rules.career.transitionAction": "전환을 고민한다면 역할, 수입, 학습 비용을 분리해 적어 보세요.",
  "report.rules.finance.scope": "재무 흐름은 확정 수익을 예측하기보다 지출 습관과 리스크 관리 방식을 점검하는 참고 정보로 보는 편이 안전합니다.",
  "report.rules.finance.investmentRisk": "투자 판단을 대신하지 않으며, 과도한 확신이나 충동 지출은 별도로 점검해야 합니다.",
  "report.rules.finance.uncertainMoneyRisk": "불확실한 정보만으로 큰 금액을 움직이는 선택은 피하는 것이 좋습니다.",
  "report.rules.finance.budgetAction": "큰 의사결정 전 예산, 최악의 경우, 회복 기간을 함께 적어보세요.",
  "report.rules.yearly.highlight": "{year}년은 {dayLabel} 성향을 현실적인 계획으로 옮기는 데 초점을 둘 수 있습니다.",
  "report.rules.yearly.resourceHighlight": "이미 가진 자원과 관계를 정리하면 다음 선택의 여지가 더 선명해집니다.",
  "report.rules.yearly.noCertaintyCaution": "검증되지 않은 해석을 확정 정보로 받아들이지 말고, 중요한 결정은 현실 자료와 함께 보완해야 합니다.",
  "report.rules.yearly.smallMetricsCaution": "빠른 결론보다 반복해서 확인할 수 있는 작은 지표를 두는 편이 안전합니다.",
  "report.rules.month.cautionNote": "속도보다 점검을 우선하면 부담을 줄일 수 있습니다.",
  "report.rules.actions.habitRecord": "하루 한 번 오늘의 선택과 감정 변화를 짧게 기록해 보세요.",
  "report.rules.actions.monthlyPlanning": "목표를 한 달 단위로 나누고, 실행 기준과 중단 기준을 함께 정해 보세요.",
  "report.rules.actions.careerFinanceCompare": "커리어와 재무 선택은 기대 효과와 비용을 분리해서 비교하는 방식이 좋습니다.",
  "report.rules.actions.noCertainAdvice": "단정적 조언이나 확정 수익처럼 들리는 정보는 한 번 더 검토하세요.",
  "report.rules.actions.expertRealityCheck": "중요한 선택은 전문가 조언과 현실 자료를 함께 확인하는 보조 도구로만 활용하세요.",
  "report.rules.transparency.birthDate": "입력된 생년월일: {birthDate}",
  "report.rules.transparency.timezone": "타임존: {timezone}",
  "report.rules.transparency.dayPillar": "계산된 일주: {dayPillar}",
  "report.rules.transparency.pillarMeaning": "연주, 월주, 일주, 시주는 사주 구조를 나눠 보는 표시입니다. 각각 큰 흐름, 환경, 나의 중심, 세부 흐름을 읽는 데 사용합니다.",
  "report.rules.transparency.ruleBased": "성향, 커리어, 재무 문장은 계산된 기둥을 바탕으로 한 규칙 기반 해석이며 확정적 예측이 아닙니다.",
  "report.rules.transparency.fixtureRange": "현재 계산 코어는 내장된 검증 fixture 범위에서 우선 동작하며, 절기 데이터 범위는 단계적으로 확장됩니다.",
  "report.rules.transparency.missingBirthTime": "출생시간 정보가 없어 시주와 일부 해석의 신뢰도가 낮아질 수 있습니다.",
  "report.rules.tone.gap.label": "성장",
  "report.rules.tone.gap.summary": "새로운 방향을 열고 가능성을 키우는 힘이 두드러집니다.",
  "report.rules.tone.gap.strength": "초기 아이디어를 만들고 장기적인 방향을 세우는 데 강점이 있습니다.",
  "report.rules.tone.gap.blindSpot": "가능성을 넓히는 과정에서 우선순위가 흐려질 수 있습니다.",
  "report.rules.tone.gap.career": "커리어에서는 새 과제나 역할 확장처럼 성장 여지가 있는 선택지가 잘 맞습니다.",
  "report.rules.tone.gap.finance": "재무에서는 확장보다 기반을 먼저 확인할 때 안정감이 커집니다.",
  "report.rules.tone.gap.action": "새로운 선택지는 목표, 비용, 회복 시간을 함께 적어 보세요.",
  "report.rules.tone.eul.label": "조율",
  "report.rules.tone.eul.summary": "상황을 살피며 부드럽게 방향을 조정하는 힘이 드러납니다.",
  "report.rules.tone.eul.strength": "관계를 읽고 작은 변화를 꾸준히 쌓는 데 강점이 있습니다.",
  "report.rules.tone.eul.blindSpot": "주변 흐름을 많이 고려하다가 결정이 늦어질 수 있습니다.",
  "report.rules.tone.eul.career": "커리어에서는 협업, 운영, 개선처럼 조율이 필요한 역할에서 힘이 납니다.",
  "report.rules.tone.eul.finance": "재무에서는 작은 지출과 반복 비용을 정리할 때 효과가 큽니다.",
  "report.rules.tone.eul.action": "결정 기준을 세 가지 이하로 줄이면 실행 속도를 높일 수 있습니다.",
  "report.rules.tone.byeong.label": "표현",
  "report.rules.tone.byeong.summary": "생각을 밖으로 드러내고 흐름을 밝히는 힘이 있습니다.",
  "report.rules.tone.byeong.strength": "상황을 설명하고 사람들을 움직이게 하는 표현력이 강점입니다.",
  "report.rules.tone.byeong.blindSpot": "속도가 빨라질수록 세부 검토가 부족해질 수 있습니다.",
  "report.rules.tone.byeong.career": "커리어에서는 발표, 설득, 기획처럼 메시지를 전달하는 일이 어울립니다.",
  "report.rules.tone.byeong.finance": "재무에서는 즉흥적 선택보다 기록과 비교가 필요합니다.",
  "report.rules.tone.byeong.action": "중요한 제안은 하루 뒤 다시 읽고 숫자 조건을 확인하세요.",
  "report.rules.tone.jeong.label": "집중",
  "report.rules.tone.jeong.summary": "작은 불씨를 오래 지키듯 한 주제에 집중하는 힘이 있습니다.",
  "report.rules.tone.jeong.strength": "섬세한 관찰과 꾸준한 개선에 강점이 있습니다.",
  "report.rules.tone.jeong.blindSpot": "완성도를 높이려다 피로를 쌓을 수 있습니다.",
  "report.rules.tone.jeong.career": "커리어에서는 전문성을 쌓거나 품질을 다듬는 역할이 잘 맞습니다.",
  "report.rules.tone.jeong.finance": "재무에서는 소액이라도 규칙적으로 관리하는 방식이 유리합니다.",
  "report.rules.tone.jeong.action": "해야 할 일을 작게 나누고 마감 기준을 먼저 정해 보세요.",
  "report.rules.tone.mu.label": "안정",
  "report.rules.tone.mu.summary": "흔들리는 상황을 붙잡고 기준을 세우는 힘이 있습니다.",
  "report.rules.tone.mu.strength": "복잡한 일을 구조화하고 책임 있게 버티는 데 강점이 있습니다.",
  "report.rules.tone.mu.blindSpot": "변화가 필요한 순간에도 익숙한 방식을 오래 유지할 수 있습니다.",
  "report.rules.tone.mu.career": "커리어에서는 관리, 운영, 책임 범위가 분명한 역할이 잘 맞습니다.",
  "report.rules.tone.mu.finance": "재무에서는 현금 흐름과 안전 여력을 확보할수록 선택지가 넓어집니다.",
  "report.rules.tone.mu.action": "큰 결정을 하기 전 유지 비용과 회복 기간을 먼저 계산하세요.",
  "report.rules.tone.gi.label": "정리",
  "report.rules.tone.gi.summary": "흩어진 정보를 모아 현실적인 형태로 정리하는 힘이 있습니다.",
  "report.rules.tone.gi.strength": "세부 조건을 살피고 실용적인 방법을 찾는 데 강점이 있습니다.",
  "report.rules.tone.gi.blindSpot": "검토가 길어지면 기회를 놓쳤다고 느낄 수 있습니다.",
  "report.rules.tone.gi.career": "커리어에서는 지원, 분석, 프로세스 개선처럼 현실 감각이 필요한 일이 어울립니다.",
  "report.rules.tone.gi.finance": "재무에서는 예산표, 지출 분류, 자동 저축처럼 체계가 도움이 됩니다.",
  "report.rules.tone.gi.action": "완벽한 계획보다 이번 주에 확인할 숫자 하나를 정해 보세요.",
  "report.rules.tone.gyeong.label": "기준",
  "report.rules.tone.gyeong.summary": "선택지를 분명히 나누고 기준을 세우는 힘이 있습니다.",
  "report.rules.tone.gyeong.strength": "판단 기준을 세우고 불필요한 것을 덜어내는 데 강점이 있습니다.",
  "report.rules.tone.gyeong.blindSpot": "기준이 강해질수록 유연한 협의가 어려워질 수 있습니다.",
  "report.rules.tone.gyeong.career": "커리어에서는 문제 해결, 기준 수립, 품질 관리 성격의 일이 잘 맞습니다.",
  "report.rules.tone.gyeong.finance": "재무에서는 손실 한도와 지출 상한을 미리 정하는 것이 중요합니다.",
  "report.rules.tone.gyeong.action": "선택 전 중단 기준과 재검토 시점을 함께 정하세요.",
  "report.rules.tone.sin.label": "정밀",
  "report.rules.tone.sin.summary": "세부를 정확히 보고 완성도를 높이는 힘이 있습니다.",
  "report.rules.tone.sin.strength": "작은 차이를 발견하고 결과물을 다듬는 데 강점이 있습니다.",
  "report.rules.tone.sin.blindSpot": "비판적 기준이 높아 스스로에게 압박이 커질 수 있습니다.",
  "report.rules.tone.sin.career": "커리어에서는 검토, 편집, 데이터, 품질 중심의 역할이 어울립니다.",
  "report.rules.tone.sin.finance": "재무에서는 계약 조건과 수수료처럼 작은 항목을 확인할수록 좋습니다.",
  "report.rules.tone.sin.action": "완료 기준을 먼저 정하고 남은 개선은 다음 단계로 넘겨 보세요.",
  "report.rules.tone.im.label": "탐색",
  "report.rules.tone.im.summary": "정보를 넓게 살피고 흐름을 읽는 힘이 있습니다.",
  "report.rules.tone.im.strength": "낯선 정보를 빠르게 흡수하고 대안을 찾는 데 강점이 있습니다.",
  "report.rules.tone.im.blindSpot": "선택지가 많아질수록 결론을 미루기 쉽습니다.",
  "report.rules.tone.im.career": "커리어에서는 조사, 전략, 콘텐츠, 이동성이 있는 역할에서 힘이 납니다.",
  "report.rules.tone.im.finance": "재무에서는 여러 가능성을 보되 검증되지 않은 정보는 거리를 두는 편이 안전합니다.",
  "report.rules.tone.im.action": "새 정보는 출처, 비용, 실패 시 손실을 한 줄씩 적어 보세요.",
  "report.rules.tone.gye.label": "유연",
  "report.rules.tone.gye.summary": "상황 변화에 맞춰 조용히 방향을 바꾸는 힘이 있습니다.",
  "report.rules.tone.gye.strength": "복잡한 감정과 맥락을 읽고 유연하게 대응하는 데 강점이 있습니다.",
  "report.rules.tone.gye.blindSpot": "분명한 표현을 미루면 주변이 의도를 오해할 수 있습니다.",
  "report.rules.tone.gye.career": "커리어에서는 상담, 리서치, 기획 보조, 장기 관찰이 필요한 일이 어울립니다.",
  "report.rules.tone.gye.finance": "재무에서는 불확실성이 큰 선택보다 작은 실험과 기록이 유리합니다.",
  "report.rules.tone.gye.action": "생각을 혼자 오래 두지 말고 선택 조건을 문장으로 정리해 보세요.",
  "report.rules.month.ja.goodMonths": "1월|12월",
  "report.rules.month.ja.cautionMonths": "6월",
  "report.rules.month.ja.note": "정리와 저장의 흐름이 강해 계획을 차분히 다듬기 좋습니다.",
  "report.rules.month.chuk.goodMonths": "1월|2월",
  "report.rules.month.chuk.cautionMonths": "7월",
  "report.rules.month.chuk.note": "기반을 점검하고 미뤄 둔 일을 정리하기 좋은 흐름입니다.",
  "report.rules.month.in.goodMonths": "2월|3월",
  "report.rules.month.in.cautionMonths": "8월",
  "report.rules.month.in.note": "새로운 시도를 시작하기 쉽지만 속도 조절이 필요합니다.",
  "report.rules.month.myo.goodMonths": "3월|4월",
  "report.rules.month.myo.cautionMonths": "9월",
  "report.rules.month.myo.note": "관계와 협업의 기회가 늘 수 있어 조율이 중요합니다.",
  "report.rules.month.jin.goodMonths": "4월|5월",
  "report.rules.month.jin.cautionMonths": "10월",
  "report.rules.month.jin.note": "변화 전 점검이 필요한 시기라 기준 정리가 도움이 됩니다.",
  "report.rules.month.sa.goodMonths": "5월|6월",
  "report.rules.month.sa.cautionMonths": "11월",
  "report.rules.month.sa.note": "표현과 실행력이 살아나지만 과열을 경계해야 합니다.",
  "report.rules.month.o.goodMonths": "6월|7월",
  "report.rules.month.o.cautionMonths": "12월",
  "report.rules.month.o.note": "성과를 드러내기 좋지만 무리한 확장은 피하는 편이 좋습니다.",
  "report.rules.month.mi.goodMonths": "7월|8월",
  "report.rules.month.mi.cautionMonths": "1월",
  "report.rules.month.mi.note": "현실적인 조정과 마무리 작업에 힘이 실립니다.",
  "report.rules.month.sin.goodMonths": "8월|9월",
  "report.rules.month.sin.cautionMonths": "2월",
  "report.rules.month.sin.note": "분석과 정리에 유리하지만 관계 표현은 부드럽게 가져가세요.",
  "report.rules.month.yu.goodMonths": "9월|10월",
  "report.rules.month.yu.cautionMonths": "3월",
  "report.rules.month.yu.note": "결과물을 다듬고 기준을 세우기 좋은 흐름입니다.",
  "report.rules.month.sul.goodMonths": "10월|11월",
  "report.rules.month.sul.cautionMonths": "4월",
  "report.rules.month.sul.note": "책임과 마무리가 중요해지는 흐름입니다.",
  "report.rules.month.hae.goodMonths": "11월|12월",
  "report.rules.month.hae.cautionMonths": "5월",
  "report.rules.month.hae.note": "탐색과 회복에 유리하지만 결정은 천천히 확인하세요."
} as const;

export function reportCopy(key: ReportCopyKey): string {
  return REPORT_COPY_KO[key];
}

export function formatReportCopy(key: ReportCopyKey, values: Record<string, string | number>): string {
  return reportCopy(key).replace(/\{(?<name>[a-zA-Z0-9]+)\}/g, (match, name: string) => {
    const value = values[name];
    return value === undefined ? match : String(value);
  });
}
